model:
  in_channels: 1
  image_size: 28
  patch_size: 4
  embedding_dim: 120
  hidden_dim: 256
  num_blocks: 7
  num_heads: 6
  out_dim: 10
  dropout: 0.1
  use_diff_attention: True

data:
  name: MNIST
  batch_size: 128
  data_dir: ./data
  num_workers: 4

trainer:
  max_epochs: 3
  logger:
    save_dir: logs
    name: ViT
