model:
  in_channels: 1
  image_size: 28
  patch_size: 4
  embedding_dim: 64
  hidden_dim: 128
  num_blocks: 2
  num_heads: 2
  out_dim: 10
  dropout: 0.1
  use_diff_attention: True

data:
  name: MNIST
  batch_size: 256
  data_dir: ./data
  num_workers: 4

trainer:
  max_epochs: 10

logger:
    enabled: True
    save_dir: logs
    name: MNSITliteViTDiff

save:
  dir: ./saves/MNIST
  name: MNSITliteViTDiff_model.ckpt
