model:
  in_channels: 1
  image_size: 28
  patch_size: 4
  embedding_dim: 32
  hidden_dim: 128
  num_blocks: 4
  num_heads: 4
  out_dim: 10
  dropout: 0.1
  use_diff_attention: False

data:
  name: MNIST
  batch_size: 128
  data_dir: ./data
  num_workers: 4

trainer:
  max_epochs: 10

logger:
    enabled: True
    save_dir: logs
    name: MNSITliteViT

save:
  dir: ./saves/FashionMNIST
  name: MNSITliteViT_model.ckpt
