model:
  in_channels: 1
  image_size: 28
  patch_size: 7
  embedding_dim: 32
  hidden_dim: 128
  num_blocks: 2
  num_heads: 2
  out_dim: 10
  dropout: 0.1
  use_diff_attention: False

data:
  name: FashionMNIST
  batch_size: 128
  data_dir: ./data
  num_workers: 4

trainer:
  max_epochs: 30

logger:
    enabled: True
    save_dir: logs
    name: FashionMNSITliteViT

save:
  dir: ./saves/MNIST/
  name: FashionMNSITliteViT_model.ckpt
