model:
  in_channels: 1
  image_size: 28
  patch_size: 4
  embedding_dim: 32
  hidden_dim: 128
  num_blocks: 4
  num_heads: 2
  out_dim: 10
  dropout: 0.1
  use_diff_attention: True

data:
  name: FashionMNIST
  batch_size: 128
  data_dir: ./data
  num_workers: 4

trainer:
  max_epochs: 30

logger:
    enabled: True
    save_dir: logs
    name: FashionMNSITliteViTDiff

save:
  dir: ./saves/MNIST/
  name: FashionMNSITliteViTDiff_model.ckpt
