model:
  in_channels: 3
  image_size: 32
  patch_size: 8
  embedding_dim: 300
  hidden_dim: 1024
  num_blocks: 2
  num_heads: 6
  out_dim: 10
  dropout: 0.3
  use_diff_attention: False

data:
  name: CIFAR10
  batch_size: 128
  data_dir: ./data
  num_workers: 4

trainer:
  max_epochs: 50

logger:
  save_dir: logs
  name: CIFARliteViT

save:
  dir: ./saves/CIFAR10/
  name: CIFARliteViT_model.ckpt
