model:
  in_channels: 3
  image_size: 32
  patch_size: 4
  embedding_dim: 498
  hidden_dim: 1536
  num_blocks: 8
  num_heads: 6
  out_dim: 10
  dropout: 0.1
  use_diff_attention: False

data:
  name: CIFAR10
  batch_size: 128
  data_dir: ./data
  num_workers: 4

trainer:
  max_epochs: 50

logger:
    save_dir: logs
    name: liteViT_balanced

save:
  dir: ./saves/CIFAR10/
  name: liteViT_balanced_model.ckpt
